### ISSUE TITLE
Editing Gau's rages corrupts saves (FF3 US V1.0)

### ISSUE THREAD

**Issue by Dizzy611** [KiameV/final-fantasy-vi-save-editor#1]
I'm not 100% sure you've got the right offsets for Gau's rages. For one thing, I had just acquired him and your editor thought I had MagicJar already (which is impossible). A number of other rages were checked that I had not acquired, and some that I had. Curious as to why this was, I attempted to select all rages and the result was major corruption of the save file. Specifically, it appeared as though the "config" section of the file had been trashed, as my controller had been completely remapped (in a way that all buttons other than the directionals made terra walk down, make me unable to get to the menu at all), and the menu graphics were completely messed up, becoming a series of multicolored pastel triangles.

Other edits (such as character stats, names, GP, etc) seem to work just fine, it's just Gau's rages that appear to be messed up.

**Comment by KiameV** [comment]
Hmm that's not good. I hope you had it backed up!

Curious what emulator are you using. Also was this a save state or a game save that you were editing?

Thanks

**Comment by Dizzy611** [comment]
the emulator was lr-snes9x and it was an srm

**Comment by KiameV** [comment]
Thank you for your help and reporting the issue.

It should be fixed now - the release's zip has been updated. Please let me know if there are any other problems you run into.
