### ISSUE TITLE
Map Data crash

### ISSUE THREAD

**Issue by hsramm** [KiameV/final-fantasy-vi-save-editor#10]
Clicking on "Map Data" crashes the application. I think it's because the file that is being loaded is saved inside a dungeon and not out in the open world. Speaking of "Map Data", any chance to add a "Teleport to Deathgaze" option somewhere? Flying around trying to find this guy is such a pain in the ass lol. If not, no biggie but I do feel the Map Data crashing the application was reportable.

**Comment by MysticalOS** [comment]
I always angled the airship almost perfect north, then just tilted it slightly east or west (doesn't matter really) then flew in a straight til encountered. deathgaze spawns in a random title on map and doesn't move. so you just need to fly through every title of map til you find right tile. This is achieved in less than 10 min if you do this as opposed to blind frantic flying.

**Comment by hsramm** [comment]
Yea, that's how I've always done it as well. It was just a suggestion to add so it wasn't so much a pain looking for it, the main part of the post was about Map Data crashing if the save file is in a dungeon and not the open world.

**Comment by KiameV** [comment]
Death Gaze's location is randomized within the game is my guess. No reference to him in the save.

Fixed crash issue with version 1.9.4
