### ISSUE TITLE
Crashing in loading save file.

### ISSUE THREAD

**Issue by Bielito23** [KiameV/final-fantasy-vi-save-editor#11]
So, it's my first time here and i don't know what happened, but after loading the save file which i generally change things (It's PR btw) the editor simply crash and there's no crash screen.

It must have been something that was changed that caused this because i checked with the other file which i never tampered with and it's working normally.

**Comment by MagicalSenpai** [comment]
I am also getting the same issue, however I have managed to capture the error output.   Please let me know if you'd like for me to attach my save file somewhere.

panic: runtime error: index out of range [9] with length 9

goroutine 24 [running]:
ffvi_editor/io/pr.(*PR).loadCharacters(0xc0002a00f0)
        C:/Users/travis/workspace/FF6Editor/io/pr/loader.go:266 +0xc7a
ffvi_editor/io/pr.(*PR).Load(0xc0002a00f0, {0xc000126180, 0xb})
        C:/Users/travis/workspace/FF6Editor/io/pr/loader.go:114 +0x4e7
ffvi_editor/ui/file.(*FileSelector).drawLoadButton(0x14ff698, 0xc000162000, 0x1496340)
        C:/Users/travis/workspace/FF6Editor/ui/file/selector.go:79 +0x1a8
ffvi_editor/ui/file.(*FileSelector).DrawLoad(0xc000162000, 0xc000162000)
        C:/Users/travis/workspace/FF6Editor/ui/file/selector.go:66 +0x4c7
main.updateWindow(0xc000162000)
        C:/Users/travis/workspace/FF6Editor/main.go:149 +0x10af
github.com/aarzilli/nucular.(*context).updateWindow(0xc0002a6000, 0xc000162000)
        C:/Users/travis/workspace/go/pkg/mod/github.com/aarzilli/nucular@v0.0.0-20210408133902-d3dd7b05a80a/context.go:97 +0x45
github.com/aarzilli/nucular.(*context).Update(0xc0002a6000)
        C:/Users/travis/workspace/go/pkg/mod/github.com/aarzilli/nucular@v0.0.0-20210408133902-d3dd7b05a80a/context.go:77 +0x105
github.com/aarzilli/nucular.(*masterWindow).updateLocked(0xc0001202c0)
        C:/Users/travis/workspace/go/pkg/mod/github.com/aarzilli/nucular@v0.0.0-20210408133902-d3dd7b05a80a/shiny.go:297 +0x189
github.com/aarzilli/nucular.(*masterWindow).updater.func1(0xc0001202c0, 0xc000067faf)
        C:/Users/travis/workspace/go/pkg/mod/github.com/aarzilli/nucular@v0.0.0-20210408133902-d3dd7b05a80a/shiny.go:263 +0x328
github.com/aarzilli/nucular.(*masterWindow).updater(0x0)
        C:/Users/travis/workspace/go/pkg/mod/github.com/aarzilli/nucular@v0.0.0-20210408133902-d3dd7b05a80a/shiny.go:277 +0x31
created by github.com/aarzilli/nucular.(*masterWindow).main
        C:/Users/travis/workspace/go/pkg/mod/github.com/aarzilli/nucular@v0.0.0-20210408133902-d3dd7b05a80a/shiny.go:122 +0x1e5

**Comment by KiameV** [comment]
hmm interesting. Looks like the save is loading and then the code fails to populate a value correctly. If you could email me at
toffty at hotmail dot com
i'll take a look. Thanks!

**Comment by MagicalSenpai** [comment]
I sent the e-mail, let me know if you need anything else.

**Comment by KiameV** [comment]
Thanks for the files, it should work now!
version 1.9.5
Feel free to re-open if you run into an issue
