### ISSUE TITLE
Editor crashes when I try to load save file

### ISSUE THREAD

**Issue by CloudCorn1814** [KiameV/final-fantasy-vi-save-editor#12]
I don't understand what is the problem, but exe file crashes.

**Comment by mrmeyers01** [comment]
same w/ me, editor crashes regardless which save file i use
this applies to both srm files and zst files, none seem to work

**Comment by thenotoriouskek** [comment]
i've got the same issue. no matter what version it just crashes the instant it loads the file.

**Comment by KiameV** [comment]
After the last update, the file structure changed and I have not had the time to get back to it sadly.

**Comment by KiameV** [comment]
Finally getting back to this. If you're still interested, you can test out the new version:
https://github.com/KiameV/final-fantasy-vi-save-editor/releases/tag/3.0.0_R1

**Comment by thenotoriouskek** [comment]
does the new editor work on .srm files?

**Comment by KiameV** [comment]
Currently the new version does not.

See if the (much) older editor works:
https://github.com/KiameV/final-fantasy-vi-save-editor/releases/tag/old
