### ISSUE TITLE
Item without a description in the inventory list

### ISSUE THREAD

**Issue by onmyouji** [KiameV/final-fantasy-vi-save-editor#13]
Hi,

In my inventory list, there's an item with id 197 without any description. 

![Copy_of_2022-08-01_150035](https://user-images.githubusercontent.com/8424198/182110770-2e66d183-c535-4602-9533-8730a1c4c57a.png)

I tried to open other user's save file on the editor and I noticed this item also exists on their save file, item 197 with 5 quantity (also without any name/description).

I wonder whether this is a bug or item 197 actually refers to real item. If it is the latter, what item is it?

**Comment by KiameV** [comment]
I should add this somewhere, 197 is an internal FF6 PR value for 'nothing
equipped in this slot" for characters

**Comment by onmyouji** [comment]
Thanks for the reply.

So this value is not useful for the player and should be left untouched?

If I accidentally change it, will it corrupt the save file? If yes, can I suggest not to display the value and remove it from the editor?

**Comment by KiameV** [comment]
The reason it's not hidden is there wasn't a good way to with the UI I'm
using. I've added protections in the code to make sure the value doesn't go
lower than it should. If it's increased it won't do anything.

I agree it's not perfect having it shown and I could probably find a way to
disable that field at the least. I'll keep this open as a reminder.
