### ISSUE TITLE
Wont load ff6 pixel remaster saves

### ISSUE THREAD

**Issue by Question2** [KiameV/final-fantasy-vi-save-editor#16]
Just gives an error message : 
![image](https://github.com/KiameV/final-fantasy-vi-save-editor/assets/1191378/b73ae747-ab85-43aa-a873-d32e1e719311)

**Comment by Question2** [comment]
@KiameV

**Comment by Question2** [comment]
[ff6 saves.zip](https://github.com/KiameV/final-fantasy-vi-save-editor/files/12430283/ff6.saves.zip)

Here are my saves just in case

**Comment by yakaru** [comment]
Are you using a non-Latin language for character names?

**Comment by mm314601** [comment]
I'm seeing the same issue. I left all the character names as their defaults.
![image](https://github.com/KiameV/final-fantasy-vi-save-editor/assets/31632560/0d0dacb3-fd1f-4173-b481-dd62d5ba7d09)
Edit: I was able to find a solve. Turns out my system's Administrative Language Settings had this setting:
![image](https://github.com/KiameV/final-fantasy-vi-save-editor/assets/31632560/295f3e8d-f5e4-4940-ba95-2c7dee341de4)
Changing that to English and restarting let me load my files. Learned something!

**Comment by KiameV** [comment]
Finally getting back to this. If you're still interested, you can test out the new version:
https://github.com/KiameV/final-fantasy-vi-save-editor/releases/tag/3.0.0_R1

**Comment by yakaru** [comment]
Hey,
![image_2024-06-12_230700335](https://github.com/KiameV/final-fantasy-vi-save-editor/assets/5253376/7b0acc7b-a755-426b-bb9b-86b2d666c5df)
Getting a bunch of Unicode unknowns but it does load and otherwise look correct.

**Comment by KiameV** [comment]
Awesome!
The GUI library I'm using will better support unicode with the next
version. There is a work around that I've added and will detail as I get
closer to release.

Thanks for testing this

**Comment by mm314601** [comment]
> Finally getting back to this. If you're still interested, you can test out the new version: https://github.com/KiameV/final-fantasy-vi-save-editor/releases/tag/3.0.0_R1

Hmm, my anti-virus keeps flagging the new version as a Trojan and deleting it automatically. And frankly, I'm just paranoid enough to not want to force it to ignore the file. I'm not sure what's different in the new version that it's getting flagged as a Trojan and the old one wasn't, of course, but thought you should know anyway.

**Comment by KiameV** [comment]
Just posted the full release. Can try that. Let me know if the newest
version also flags and I'll file a ticket to get it white flagged.

What anti-virus are you using by chance?

**Comment by mm314601** [comment]
I'm using Kaspersky, which I admit has a habit of falsely flagging things. However, the latest release did not get flagged by anti-virus. Windows Defender didn't like it, but that's really not a surprise at all. Thank you!
