### ISSUE TITLE
Crashes on Steam Deck

### ISSUE THREAD

**Issue by calvinpark** [KiameV/final-fantasy-vi-save-editor#18]
1. Went into Steam Deck desktop mode.
2. Made a symlink from `~/.local/share/Steam/steamapps/compatdata` to `/opt/compat` since the browser doesn't show hidden directories.
3. Registered the .exe as a non-Steam game, enabled Proton Experimental, set controls to mouse mode, and ran.
4. Clicked `Load Remaster` and selected `Z:\opt\compat\1173820\<save dir>`. Now I see `Load Quick Save`, `Load slot 1` and , `Load slot 2`.
5. Clicking any of the three `Load` buttons crashes the editor exe.

**Comment by KiameV** [comment]
If you're still interested, you can see if the new version runs:
https://github.com/KiameV/final-fantasy-vi-save-editor/releases/tag/3.0.0_R1

Currently only compiling a windows version in releases
