### ISSUE TITLE
404 nonsense

### ISSUE THREAD

**Issue by Liunjiich** [KiameV/final-fantasy-vi-save-editor#22]
For some reason anytime I try to download off the install link you have on the page all I get is a 404. So I guess I'm just straight outta luck on this one it seems.

**Comment by KiameV** [comment]
Which download page are you referring to? In the app or from a site?

https://github.com/KiameV/final-fantasy-vi-save-editor/releases/download/3.2.0/FFVIPR_Save_Editor.exe
Is the latest version
