### ISSUE TITLE
Moogle bug

### ISSUE THREAD

**Issue by ThePutois** [KiameV/final-fantasy-vi-save-editor#4]
Hello,

Your tool is great, but I think data is misaligned on Moogle, like the default equipment values are that his spear is on the shield slot or something like that, I just got him in World of Balance and now the game is killed because I can't change his equipement, and entering in a battle freezes the whole party, is there a fix? 

Thanks

edit : screenshot of equipment screen
![FINAL_FANTASY_VI_daeZZBaya3](https://user-images.githubusercontent.com/66801022/159121087-a4744ba9-a10c-4f4f-bf9b-5c713dc47eda.png)

**Comment by KiameV** [comment]
Are you on the most recent version? 1.5.2

If you are can you send me the file? Toffty at hotmail dot com.

**Comment by ThePutois** [comment]
I was on 1.5.1 when I first modified the file yesterday, but didn't touch anything Mog related. Only did today when I got him on my team and I used the 1.5.2. I send you the save file now

**Comment by KiameV** [comment]
Fixed with 1.5.3

**Comment by KiameV** [comment]
Are you on the most recent version? 1.5.2

If you are can you send me the file? Toffty at hotmail dot com.
