### ISSUE TITLE
Can't Load Save with Japanese Save

### ISSUE THREAD

**Issue by kyoniichan** [KiameV/final-fantasy-vi-save-editor#7]
I receive this error when I try to load a save.
![image](https://user-images.githubusercontent.com/48494553/167045834-6d2ae279-9af2-4710-961f-1293dad38cf4.png)
I googled it and found this https://gomilkyway.com/ja/misc/cp932-codec-cant-encode-character-xa1-in-position-62-illegal-multibyte-sequence/ so I believe it may be caused by me playing in Japanese?
I'm happy to provide any other information you may feel is relevant.
Thank you for making this save editor.

**Comment by KiameV** [comment]
I've been able to support other languages but I have not figured out how to support Japanese. I'll continue to try though.

**Comment by KiameV** [comment]
Finally getting back to this. If you're still interested, you can test out the new version:
https://github.com/KiameV/final-fantasy-vi-save-editor/releases/tag/3.0.0_R1
