### ISSUE TITLE
Bestiary Editor/Fixer

### ISSUE THREAD

**Issue by MysticalOS** [KiameV/final-fantasy-vi-save-editor#8]
If you are like me and missed something that is not encounterable again, it'd be nice to be able to manually add the missed enemy to bestiary. Fortunately you can kind of do that with veldt encounter flagging. Just flag the enemy you need and unflag the ones you don't then go to veldt and encounter it, But it'd still be cool to not do it in a way that doesn't make one have to kinda hose the actual encounters they had flagged on veldt.

Great tool btw, it's been fun to replay a classic on pixel remaster but it's also kinda game I've 100% so many times, I just kinda want to goof off with it this time (ie enjoy it and not be obsessed over esper level up management and other tediums that I've done enough times in my life already). :)

**Comment by KiameV** [comment]
Yeah I hear you. Encounter flags don't appear to be in the save files though. It might be in one of the other files in the save directory or somewhere in the code files. Not sure at this point.

**Comment by KiameV** [comment]
I followed the hunch and i found the file. I'll brainstorm how to integrate it....

**Comment by MysticalOS** [comment]
Ah yes, must be a profile save that exists for the collective of saves i assume?

**Comment by KiameV** [comment]
1.9.3 will now complete the Bestiary as well as Visit All Locations achievements!
