### ISSUE TITLE
Missing/Incorrect Item name for Murasame

### ISSUE THREAD

**Issue by hsramm** [KiameV/final-fantasy-vi-save-editor#9]
![image](https://user-images.githubusercontent.com/36422849/170807105-63bfa200-b5f6-415f-8760-202791c3c198.png)

"Murasame" can't be found when searched because it goes by the name of "Masamane" which isn't even an item.

**Comment by KiameV** [comment]
In PR I believe it's called "Masamune". You can see the list of "Katana" in
the text box that starts with "Dirk"

**Comment by KiameV** [comment]
fixed with 1.9.4
